# Generated by Django 2.2 on 2019-04-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_date',
            new_name='date_enquiry_made',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_property',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_person_mail',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
