# Generated by Django 2.2 on 2019-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/profile_default.png', upload_to='images/'),
        ),
    ]
