# Generated by Django 2.2 on 2019-04-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190405_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/media/images/profile_default.png', upload_to='images/'),
        ),
    ]
